---
- name: 
  hosts: all
  become: true
  vars:
    git_repository: "https://github.com/pandalukasz/Ansible_roles.git"
    git_branch: "master"
  tasks:
    - name: Tworze katalog
      file:
        path: /etc/ansible/roles
        state: directory
        mode: '0755'
    - name: Mapowanie gita
      git:
        repo: "{{ git_repository }}"
        dest: "/etc/ansible/roles"
        version: "{{ git_branch }}"